spring:
  datasource:
    url: jdbc:sqlserver://apt3095project.database.windows.net:1433;database=to_do_list;user=apt3095_project@apt3095project;password={todolist-1};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: apt3095_project
    password: todolist-1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9191